kind: playground
name: uncloud-uninitialized-cluster-cacb63ae
base: flexbox
title: 'Uncloud: Uninitialized Cluster'
description: This is a helper playground used as a starting point for some Uncloud [tutorials](https://labs.iximiuz.com/tutorials).
categories:
    - linux
    - networking
    - containers
playground:
    networks:
        - name: local
          subnet: 172.16.0.0/24
    machines:
        - name: dev-machine
          users:
            - name: root
            - name: laborant
              default: true
              welcome: "Welcome to the Uncloud playground \U0001F64C\n\nYou’re currently on a control node with the installed \"uc\" CLI client.\nThere are two servers reachable from this node: server-1 and server-2.\n\n---\nAbout Uncloud: https://github.com/psviderski/uncloud/  \nDocumentation: https://uncloud.run/docs/\n"
          drives:
            - source: oci://ghcr.io/tonyo/uncloud-labs/rootfs:uncloud-devmachine
              mount: /
              size: 10GIB
          network:
            interfaces:
                - network: local
          resources:
            cpuCount: 1
            ramSize: 1GiB
        - name: server-1
          users:
            - name: root
            - name: laborant
              default: true
          drives:
            - source: ubuntu-24-04
              mount: /
              size: 10GIB
          network:
            interfaces:
                - network: local
          resources:
            cpuCount: 1
            ramSize: 2GiB
        - name: server-2
          users:
            - name: root
            - name: laborant
              default: true
          drives:
            - source: ubuntu-24-04
              mount: /
              size: 10GIB
          network:
            interfaces:
                - network: local
          resources:
            cpuCount: 1
            ramSize: 2GiB
    tabs:
        - id: terminal-dev-machine
          kind: terminal
          name: dev-machine
          machine: dev-machine
        - id: terminal-server-1
          kind: terminal
          name: server-1
          machine: server-1
        - id: terminal-server-2
          kind: terminal
          name: server-2
          machine: server-2
    accessControl:
        canList:
            - anyone
        canRead:
            - anyone
        canStart:
            - anyone
